"""init schema

Revision ID: 80c706a1e657
Revises:
Create Date: 2025-11-11 15:36:51.101706

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "80c706a1e657"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "content_atoms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("locale", sa.String(length=8), nullable=True),
        sa.Column("topic_tag", sa.String(length=64), nullable=True),
        sa.Column("style", sa.String(length=32), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_content_atoms_locale"), "content_atoms", ["locale"], unique=False
    )
    op.create_index(
        op.f("ix_content_atoms_topic_tag"), "content_atoms", ["topic_tag"], unique=False
    )
    op.create_table(
        "modules_registry",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("module", sa.String(length=64), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("config", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("module"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tg_user_id", sa.String(length=64), nullable=False),
        sa.Column("locale", sa.String(length=8), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_tg_user_id"), "users", ["tg_user_id"], unique=True)
    op.create_table(
        "birth_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("birth_date", sa.Date(), nullable=False),
        sa.Column("birth_time", sa.String(length=8), nullable=True),
        sa.Column("tz", sa.String(length=64), nullable=True),
        sa.Column("place", sa.String(length=128), nullable=True),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("lon", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_birth_data_user_id"), "birth_data", ["user_id"], unique=False
    )
    op.create_table(
        "deliveries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("module", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column("sent_at", sa.DateTime(), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_deliveries_sent_at"), "deliveries", ["sent_at"], unique=False
    )
    op.create_index(
        op.f("ix_deliveries_user_id"), "deliveries", ["user_id"], unique=False
    )
    op.create_table(
        "entitlements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("plan", sa.String(length=32), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_entitlements_user_id"), "entitlements", ["user_id"], unique=False
    )
    op.create_table(
        "events_feedback",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("event_ref", sa.String(length=64), nullable=True),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_events_feedback_event_ref"),
        "events_feedback",
        ["event_ref"],
        unique=False,
    )
    op.create_index(
        op.f("ix_events_feedback_user_id"), "events_feedback", ["user_id"], unique=False
    )
    op.create_table(
        "natal_cache",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", name="uq_natalcache_user"),
    )
    op.create_index(
        op.f("ix_natal_cache_user_id"), "natal_cache", ["user_id"], unique=False
    )
    op.create_table(
        "transit_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("ts_utc", sa.DateTime(), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transit_events_ts_utc"), "transit_events", ["ts_utc"], unique=False
    )
    op.create_index(
        op.f("ix_transit_events_user_id"), "transit_events", ["user_id"], unique=False
    )
    op.create_index(
        "ix_transit_user_ts", "transit_events", ["user_id", "ts_utc"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_transit_user_ts", table_name="transit_events")
    op.drop_index(op.f("ix_transit_events_user_id"), table_name="transit_events")
    op.drop_index(op.f("ix_transit_events_ts_utc"), table_name="transit_events")
    op.drop_table("transit_events")
    op.drop_index(op.f("ix_natal_cache_user_id"), table_name="natal_cache")
    op.drop_table("natal_cache")
    op.drop_index(op.f("ix_events_feedback_user_id"), table_name="events_feedback")
    op.drop_index(op.f("ix_events_feedback_event_ref"), table_name="events_feedback")
    op.drop_table("events_feedback")
    op.drop_index(op.f("ix_entitlements_user_id"), table_name="entitlements")
    op.drop_table("entitlements")
    op.drop_index(op.f("ix_deliveries_user_id"), table_name="deliveries")
    op.drop_index(op.f("ix_deliveries_sent_at"), table_name="deliveries")
    op.drop_table("deliveries")
    op.drop_index(op.f("ix_birth_data_user_id"), table_name="birth_data")
    op.drop_table("birth_data")
    op.drop_index(op.f("ix_users_tg_user_id"), table_name="users")
    op.drop_table("users")
    op.drop_table("modules_registry")
    op.drop_index(op.f("ix_content_atoms_topic_tag"), table_name="content_atoms")
    op.drop_index(op.f("ix_content_atoms_locale"), table_name="content_atoms")
    op.drop_table("content_atoms")
    # ### end Alembic commands ###
